### PR TITLE
Update callback.js

### PR DESCRIPTION
**Pull request by Zack-Dx**
Improving the callback check.

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@verlok Hey mate can you please merge this if it had no issues.

**Comment by verlok** [comment]
Hey @Zack-Dx,
Thank you for opening this. 

How does that improve the callback check?
What is the use case that is covered by this change?

**Comment by Zack-Dx** [comment]
> Hey @Zack-Dx, Thank you for opening this.
> 
> How does that improve the callback check? What is the use case that is covered by this change?

It ensures that the passed function/argument is a callback and not just a true value, hence it can help to avoid `callback is not a function` error.

**Comment by verlok** [comment]
Ok, could you change only the tuo check and not everything else?

**Comment by Zack-Dx** [comment]
> Ok, could you change only the tuo check and not everything else?

done. Thanks!

**Comment by verlok** [comment]
Hello again, and thank you. 
There's another small thing to do: you can't merge to `master` directly. 
Your merge destination should be `development`. 
Are you able to change that?

**Comment by Zack-Dx** [comment]
> Hello again, and thank you. There's another small thing to do: you can't merge to `master` directly. Your merge destination should be `development`. Are you able to change that?

yep I think it's done.

**Comment by verlok** [comment]
Never mind, I'll apply the changes myself

**Comment by verlok** [comment]
Oh, that was fast. Thanks.

**Comment by Zack-Dx** [comment]
> Oh, that was fast. Thanks.

haha, I thought why to be lazy, anyways thanks I'll contribute more If I find such issues.

**Comment by verlok** [comment]
Released on npm and everywere else as 17.8.5

**Pull request merged**
