### PR TITLE
adds the browserlist configuration

### LINKED ISSUE #614: Browserlist Support
As suggestested by @xhmikosr [here](https://github.com/verlok/vanilla-lazyload/issues/611#issuecomment-2027675307) browserlist works in combination with babel in order to define the language lavel. The issue was related that we didn't have any :) 

**Describe the solution you'd like**
Adds the browserlist configuration

**Describe alternatives you've considered**
Babel can be completely replaced with tsc, but one step at time

### PR DESCRIPTION
**Pull request by erikyo**
Adds the configuration required for babel/browserlist.

This very simple change, however, is worth about 1/8 less code in the build

close #614

### CODE REVIEW

**Comment by XhmikosR** [comment]
Isn't this the same as not having a browserslist config? I would expect so...

What's the `du -h` of the dist folder before and after this change after running dist?

**Comment by erikyo** [comment]
Seems not, the output is a bit different with and without those lines

```bash
# with browserlist 
du -h
24K     ./esm
128K    .

# without browserlist
du -h
24K     ./esm
136K    .
dev@B760M:/mnt/d/web/vanilla-lazyload/dist$ 
```

As a test case without browserlist i can find in the code "var myVariable" and with browserlist the output displays "const variable", so i guess to have it or to not have it changes something in the default babel config.

**Comment by XhmikosR** [comment]
Cool, then better add it explicitly and maybe adapt it later to your supported browsers

**Comment by erikyo** [comment]
Yes we will, the only thing is that I want to make sure that in older versions of safari (e.g. 12) everything still works as before because with the default browserslist configuration the last supported are:
```
safari 17.4
safari 17.3
safari 17.2
safari 16.6
safari 15.6
```

**Comment by verlok** [comment]
I have a browserstack account if we need to test on older versions of any browser.

**Comment by verlok** [comment]
In the screenshots is why the code is shorter with @erikyo's addition.

- `var` becomes `const` (2 chars more) or `let`, but 
- `function () {` becomes `()=>{` and 
- `return` statements are replaced by just the return value.

Screenshot 2024-04-03 at 14 03 26

Screenshot 2024-04-03 at 14 03 50

This code looks solid to me.

**Comment by verlok** [comment]
And ES6 is widely supported _nowadays_, see the [can I use table](https://caniuse.com/?search=es6) (or the screenshot)

Screenshot 2024-04-03 at 14 07 29

**Comment by verlok** [comment]
Also interesting the relative usage table

Screenshot 2024-04-03 at 14 09 36

**Comment by verlok** [comment]
And as I stated in [this section of the readme](https://github.com/verlok/vanilla-lazyload/blob/master/README.md#-getting-started---script), users who need to support legacy browsers can always use version 17.9.0.

There are [3.7 Billion users / month downloading version 10.19.0](https://www.jsdelivr.com/package/npm/vanilla-lazyload?tab=stats), so... ¯\_(ツ)_/¯

**Comment by erikyo** [comment]
Yep the browserslist repository is crafted very well and the default setting should be something like

`> 0.5%, last 2 versions, Firefox ESR, not dead`

which is why I don't think anyone will complain 😇

Just we need to make sure to update to the last version the current database using:

`npx update-browserslist-db@latest`

before build the new "versions" and automatically babel will use the correct polyfills according to the current world standards

**Comment by verlok** [comment]
Released

**Comment by verlok** [comment]
I added this to the build steps I follow before releasing.

```
npx update-browserslist-db@latest
```

Thanks Erik

**Pull request merged**
