### PR TITLE
Avoid DOM operation if applying an empty className

### PR DESCRIPTION
**Pull request by stanleyxu2005**
A new PR followed by #605 

Description see here https://github.com/verlok/vanilla-lazyload/pull/605#issue-2190569574
The PR includes file changes in the dist folder

### CODE REVIEW

**Comment by verlok** [comment]
Hey, thank you again, but GitHub still says you want to merge from your branch to `verlok/master`.
Apparently I'm not able to use GitHub properly, I'll need to see how to protect the main branch from PR commits.
Anyway I'll apply your changes and mention you both in the commit message and in the changelog.
I hope you're fine with that.

**Comment by stanleyxu2005** [comment]
> Hey, thank you again, but GitHub still says you want to merge from your branch to `verlok/master`. Apparently I'm not able to use GitHub properly, I'll need to see how to protect the main branch from PR commits. Anyway I'll apply your changes and mention you both in the commit message and in the changelog. I hope you're fine with that.

Oh yea. Not realized it is `main` not `master` in this project.
Please go ahead with the merge. I'm fine with that @verlok Cheers

**Comment by verlok** [comment]
I just noticed there's a data attribute being added to the elements observed by this library anyway, even if the class name is not added anymore

**Comment by stanleyxu2005** [comment]
> I just noticed there's a data attribute being added to the elements observed by this library anyway, even if the class name is not added anymore

Could you point it out, what data attribute?

**Comment by verlok** [comment]
> Could you point it out, what data attribute?

The attribute name is `data-ll-status`
It becomes `loaded` when it's an image and it's loaded.

**Comment by verlok** [comment]
Released version 17.9

**Pull request closed without merging**
